# Generated by Django 3.1.2 on 2021-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sum',
            field=models.FloatField(null=True, verbose_name='Сумма'),
        ),
    ]
