# Generated by Django 3.1.2 on 2021-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contract_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_time_contract',
            name='sum',
            field=models.FloatField(null=True, verbose_name='Сумма'),
        ),
    ]
